[package]
name = "ufotofu-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4.0", features = ["arbitrary-derive"] }
smol = "2.0.0"
ufotofu = { path = "../ufotofu", features = ["dev"] }
wrapper = "0.1.1"
either = "1.10.0"

[[bin]]
name = "slices"
path = "fuzz_targets/sync/slices.rs"
test = false
doc = false
bench = false

[[bin]]
name = "into_vec"
path = "fuzz_targets/sync/into_vec.rs"
test = false
doc = false
bench = false

[[bin]]
name = "into_vec_fallible"
path = "fuzz_targets/sync/into_vec_fallible.rs"
test = false
doc = false
bench = false

[[bin]]
name = "scramble_consumer"
path = "fuzz_targets/sync/scramble_consumer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "scramble_producer"
path = "fuzz_targets/sync/scramble_producer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "local_nb_slices"
path = "fuzz_targets/local_nb/slices.rs"
test = false
doc = false
bench = false

[[bin]]
name = "local_nb_into_vec"
path = "fuzz_targets/local_nb/into_vec.rs"
test = false
doc = false
bench = false

[[bin]]
name = "local_nb_into_vec_fallible"
path = "fuzz_targets/local_nb/into_vec_fallible.rs"
test = false
doc = false
bench = false

[[bin]]
name = "local_nb_scramble_consumer"
path = "fuzz_targets/local_nb/scramble_consumer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "local_nb_scramble_producer"
path = "fuzz_targets/local_nb/scramble_producer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sync_pipe_into_slice"
path = "fuzz_targets/sync/pipe_into_slice.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sync_bulk_pipe_into_slice"
path = "fuzz_targets/sync/bulk_pipe_into_slice.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sync_pipe_into_slice_uninit"
path = "fuzz_targets/sync/pipe_into_slice_uninit.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sync_bulk_pipe_into_slice_uninit"
path = "fuzz_targets/sync/bulk_pipe_into_slice_uninit.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sync_pipe_from_slice"
path = "fuzz_targets/sync/pipe_from_slice.rs"
test = false
doc = false
bench = false

[[bin]]
name = "local_nb_pipe_into_slice"
path = "fuzz_targets/local_nb/pipe_into_slice.rs"
test = false
doc = false
bench = false

[[bin]]
name = "local_nb_bulk_pipe_into_slice"
path = "fuzz_targets/local_nb/bulk_pipe_into_slice.rs"
test = false
doc = false
bench = false

[[bin]]
name = "local_nb_pipe_into_slice_uninit"
path = "fuzz_targets/local_nb/pipe_into_slice_uninit.rs"
test = false
doc = false
bench = false

[[bin]]
name = "local_nb_bulk_pipe_into_slice_uninit"
path = "fuzz_targets/local_nb/bulk_pipe_into_slice_uninit.rs"
test = false
doc = false
bench = false